Implementing certificate-operator Operator for managing certify certificates
dana-team/certificate-operator pull request #1
Opened 2024-04-30 11:58 UTC by arielsepton

2024-05-01 20:06 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +	r.Log.Info("cleaned up the '" + dependenciesFinalizer + "' finalizer successfully")
Not sure but maybe move this to the `handleDelete` function and make this function return `(bool, err)`, with the bool indicating if `len > 0`?

2024-05-01 20:06 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +}
Also here I'd move it upwards

2024-05-01 20:06 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +	}
Nice

2024-05-01 20:11 UTC, mzeevi commented on internal/controller/certificateconfig_controller_test.go
> +
Redundant space

2024-05-01 20:12 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +	}
Do we just get the secret for the sake of returning an error if it does not exist?

2024-05-01 20:14 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +		return errorspkg.Wrap(err, fmt.Sprintf(errFailedToGetSecret, certificateConfig.Spec.SecretRef.Name, certificateConfig.Spec.SecretRef.Namespace))
You differentiate between the errors just for the different message, but you can just do a `fmt.Errorf("failed to get secret: %v", err)` and the underlying error, whether it's IsNotFound or not would be appended. We don't unwrap the error on the caller and act differently if it's NotFound or not so I don't think this is needed

2024-05-01 20:18 UTC, mzeevi commented on internal/cert-handler/decoder.go
> +	CERTIFICATE = "CERTIFICATE"
Why is the const here in all caps?

2024-05-01 20:21 UTC, mzeevi commented on internal/cert-handler/decoder.go
> +package cert_handler
[Rename](https://google.github.io/styleguide/go/decisions#package-names) the package `certhandler`

2024-05-01 20:26 UTC, mzeevi commented on internal/clients/certify/client.go
> +func (cc *client) PostCertificate(ctx context.Context, certificateConfig *v1alpha1.CertificateConfig, certificate *v1alpha1.Certificate) (string, error) {
I know it's literally a POST request, but maybe rename it to be `IssueCertificate`?

2024-05-01 20:28 UTC, mzeevi commented on internal/clients/certify/client.go
> +func (cc *client) PostCertificate(ctx context.Context, certificateConfig *v1alpha1.CertificateConfig, certificate *v1alpha1.Certificate) (string, error) {
The receiver name should just be `c` [I think](https://google.github.io/styleguide/go/decisions#receiver-names)

2024-05-01 20:29 UTC, mzeevi commented on internal/clients/certify/client.go
> +	var responseBody PostCertificateResponse
Why is PostCertificateResponse initialized? I don't see it's used

2024-05-01 20:33 UTC, mzeevi commented on internal/clients/certify/client.go
> +	// TODO: should i validate the form field is pfx and not empty?
For now we can make the field required on the CRD level with a default to `pfx` and `enum`, but we should probably lay the foundations to supporting multiple outputs; it's probably more of a business decision so we can discuss this with Certify people to see if anyone actually uses the other forms

2024-05-01 20:35 UTC, mzeevi commented on internal/clients/certify/client.go
> +			Country:            "IL",
Is this required to not be empty?

2024-05-01 20:36 UTC, mzeevi commented on internal/clients/certify/client.go
> +// TODO: modify
What don't you like about it?

2024-05-01 20:36 UTC, mzeevi commented on internal/clients/certify/client.go
> +	}, nil
I think it's fine that it's not configurable as long as it's documented on the `README.md` properly. But move the `"token"` to be a const

2024-05-01 20:37 UTC, mzeevi commented on internal/clients/http/client.go
> +// Client is the interface to interact with Http
HTTP*

2024-05-01 20:38 UTC, mzeevi commented on internal/clients/http/client.go
> +func (hc *client) SendRequest(ctx context.Context, method string, url string, body string, headers map[string][]string, skipTLSVerify bool, timeout time.Duration) (Response, error) {
Receiver name should just be `c`

2024-05-01 20:38 UTC, mzeevi commented on internal/clients/http/client.go
> +			// #nosec G402
What does this mean?

2024-05-02 07:17 UTC, arielsepton commented on internal/clients/certify/client.go
> +func (cc *client) PostCertificate(ctx context.Context, certificateConfig *v1alpha1.CertificateConfig, certificate *v1alpha1.Certificate) (string, error) {
I think `PostCertificate` accurately reflects the action of sending data to create a new certificate, whereas `IssueCertificate` might imply receiving the certificate, which is handled by the download function.

2024-05-02 07:23 UTC, arielsepton commented on internal/clients/certify/client.go
> +	var responseBody PostCertificateResponse
The initialization of `PostCertificateResponse` is for readability and consistency with other response structs. It is referenced in the return statement to extract the `Guid` field from the response body, I think having a struct for each response enhances code clarity and understanding of the data being returned.

2024-05-02 07:26 UTC, arielsepton commented on internal/clients/certify/client.go
> +// TODO: modify
I'm unsure if all fields should always be empty.

2024-05-02 07:32 UTC, arielsepton commented on internal/clients/http/client.go
> +			// #nosec G402
The comment #nosec G402 is a directive to a security linter (gosec) to ignore the insecure use of TLSClientConfig field, which bypasses certificate verification.

2024-05-02 07:38 UTC, arielsepton commented on internal/clients/certify/client.go
> +			Country:            "IL",
I believe that field is typically required when generating certificates with OpenSSL, but to confirm definitively, we'd need to check the requirements with Certify. Their Swagger documentation doesn't specify which fields are required and which are optional.

2024-05-02 07:41 UTC, arielsepton commented on internal/cert-handler/decoder.go
> +	CERTIFICATE = "CERTIFICATE"
I used all caps for the constant `CERTIFICATE` to distinguish it from variables and emphasize that it's a constant in this context. This helps improve code readability and maintainability, especially since there's a variable named certificate in the function.

2024-05-02 07:45 UTC, arielsepton commented on internal/controller/certificateconfig_controller.go
> +	}
Yes, Without the secret, we cannot send requests to Certify, which makes the `CertificateConfig` invalid. Therefore, I validate the secret's existence before proceeding with reconciliation.

2024-05-02 07:49 UTC, arielsepton commented on internal/controller/certificate_controller.go
> +}
Shocking

2024-05-02 10:27 UTC, arielsepton commented on internal/controller/certificate_controller.go
> +		}
But you said -> both reconcilers run under the same manager so we can just specify the needed RBAC once.
Those RBAC permissions are specified in certificateconfig_controller.go

2024-05-02 10:47 UTC, arielsepton commented on internal/controller/certificate_controller.go
> +		r.updateCertificateConditions(ctx, certificate, ConditionSuccess, metav1.ConditionTrue, ConditionCertificateIssued, certIsValid)
We talked about removing positive conditions, so lmk what to do here, if any

2024-05-03 11:41 UTC, mzeevi requested changes
A few small things and I think we're good to go

2024-05-03 11:41 UTC, mzeevi commented on internal/controller/certificate_controller.go
> +}
I'm not sure about how I feel about these errors being unhandled apart from logging the error. I think we should return an error normally here and handle it at the caller. Here's a similar [example](https://github.com/dana-team/hns/blob/e8246b4a73e9efa5d2e4875d8a2bba9f79b7ab30/internal/updatequota/controller.go#L92-L98) from a different project. It kind of clatters the Reconciler and makes it less "pretty" but probably needed. WDYT?

2024-05-03 11:41 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +		return fmt.Errorf(errFailedToGetSecret, err)
I think it'd be better to return a "clean" error here and add the string context at the caller

2024-05-03 11:41 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +		return ctrl.Result{}, errorspkg.Wrap(err, fmt.Sprintf(errFailedToGetCertificateConfig, req.Name))
Is there a reason to wrap the error?

2024-05-03 11:41 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +		return errorspkg.Wrap(err, errSettingFinalizer)
Also here return a "clean" error and add the context at the caller, I think it makes reading the Reconciler function clearer so I don't have to jump to different functions to find an error string if I'm looking for it

2024-05-05 08:33 UTC, mzeevi requested changes
Last few things

2024-05-05 08:33 UTC, mzeevi commented on internal/controller/certificate_controller.go
> +	}
If the `Certificate` properties are changed in the AD-CS then we wouldn't update the changes; we should GET the latest details even if the `Certificate` is valid.

2024-05-05 08:33 UTC, mzeevi commented on internal/controller/certificateconfig_controller.go
> +	finalizers            = []string{dependenciesFinalizer}
This is unused now, no?

2024-05-05 09:00 UTC, arielsepton commented on internal/controller/certificateconfig_controller.go
> +	finalizers            = []string{dependenciesFinalizer}
moved it to the tests

2024-05-05 11:50 UTC, mzeevi approved these changes
/lgtm
/approve

2024-05-05 11:58 UTC, merged